SELECT G.TITLE, G.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE,'%Y-%m-%d')AS CREATED_DATE 
FROM USED_GOODS_BOARD AS G
JOIN USED_GOODS_REPLY AS R
ON G.BOARD_ID = R.BOARD_ID
WHERE DATE_FORMAT(G.CREATED_DATE,'%Y-%m')='2022-10' 
ORDER BY CREATED_DATE, G.TITLE;

